### ISSUE TITLE
Build fails.

### ISSUE THREAD

**Issue by mqsoh** [ua-parser/uap-java#20]
Maybe I'm using the wrong version of something? What are the requirements for this code?

I thought it might have been related to [this issue](https://github.com/ua-parser/uap-java/issues/6) but it was merged already.

```
$ docker run -it --rm maven:3.3.3-jdk-9 bash -c 'git clone https://github.com/ua-parser/uap-java.git; cd uap-java; mvn package'

[dependencies redacted]
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running ua_parser.ParserTest
Tests run: 9, Failures: 0, Errors: 9, Skipped: 0, Time elapsed: 0.163 sec <<< FAILURE!
testInvalidConfigThrows(ua_parser.ParserTest)  Time elapsed: 0.02 sec  <<< ERROR!
org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:198)
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
	at ua_parser.Parser.initialize(Parser.java:69)
	at ua_parser.Parser.<init>(Parser.java:44)
	at ua_parser.Parser.<init>(Parser.java:40)
	at ua_parser.ParserTest.initParser(ParserTest.java:43)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:533)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:533)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.io.IOException: Stream closed
	at java.io.PushbackInputStream.ensureOpen(java.base@9-internal/PushbackInputStream.java:75)
	at java.io.PushbackInputStream.read(java.base@9-internal/PushbackInputStream.java:163)
	at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
	at java.io.Reader.read(java.base@9-internal/Reader.java:140)
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
	... 35 more
```

Many more failures exactly like that, i.e. `org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed`

```
...

Running ua_parser.DeviceTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec

Results :

Tests in error: 
  testInvalidConfigThrows(ua_parser.ParserTest): java.io.IOException: Stream closed
  testParseOS(ua_parser.ParserTest): java.io.IOException: Stream closed
  testParseAdditionalOS(ua_parser.ParserTest): java.io.IOException: Stream closed
  testParseDevice(ua_parser.ParserTest): java.io.IOException: Stream closed
  testParseFirefox(ua_parser.ParserTest): java.io.IOException: Stream closed
  testParsePGTS(ua_parser.ParserTest): java.io.IOException: Stream closed
  testParseAll(ua_parser.ParserTest): java.io.IOException: Stream closed
  testParseUserAgent(ua_parser.ParserTest): java.io.IOException: Stream closed
  testReplacementQuoting(ua_parser.ParserTest): java.io.IOException: Stream closed
  testCachedParseAll(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testCachedReplacementQuoting(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testCachedParseOS(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testCachedParseUserAgent(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testCachedParseAdditionalOS(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testCachedParseDevice(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testCachedParseFirefox(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testCachedParsePGTS(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testInvalidConfigThrows(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testParseOS(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testParseAdditionalOS(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testParseDevice(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testParseFirefox(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testParsePGTS(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testParseAll(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testParseUserAgent(ua_parser.CachingParserTest): java.io.IOException: Stream closed
  testReplacementQuoting(ua_parser.CachingParserTest): java.io.IOException: Stream closed

Tests run: 35, Failures: 0, Errors: 26, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.518 s
[INFO] Finished at: 2016-07-18T21:49:30+00:00
[INFO] Final Memory: 16M/54M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ua-parser: There are test failures.
[ERROR] 
[ERROR] Please refer to /uap-java/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by mqsoh** [comment]
Never mind. I finally figured out that the ua-core repository needs to be cloned as well, i.e.

```
git clone https://github.com/ua-parser/uap-core.git
git clone https://github.com/ua-parser/uap-java.git
cd uap-java
mvn package
```

I hope this comment helps someone else in the future.

**Comment by milimetric** [comment]
Thanks!  It did help me.  Following the instructions, looks like all you need right now is a `git submodule update --init`, with all the other fancier flags like `--recursive` only theoretically needed in the future.
