### ISSUE TITLE
Test Failures

### ISSUE THREAD

**Issue by nitin12684** [ua-parser/uap-java#29]
I have clone the project but getting below exception while executing the unit test:

org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:198)
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
	at ua_parser.Parser.initialize(Parser.java:69)
	at ua_parser.Parser.<init>(Parser.java:44)
	at ua_parser.Parser.<init>(Parser.java:40)
	at ua_parser.ParserTest.initParser(ParserTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.io.IOException: Stream closed
	at java.io.PushbackInputStream.ensureOpen(PushbackInputStream.java:74)
	at java.io.PushbackInputStream.read(PushbackInputStream.java:166)
	at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:88)
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:118)
	at java.io.Reader.read(Reader.java:140)
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:182)
	... 29 more

I didn't find any regexes.yaml file in the source code. Am I missing something?

**Comment by nitin12684** [comment]
Issue resolved by including core resources. Few test cases are failing but manageable.

**Comment by nitin12684** [comment]
Closing the issue.
